[[redirects]]
  from = "/*"
  to = "https://tech-ticketing-0481f8c73394.herokuapp.com/:splat"
  status = 200
  force = true
  headers = { Access-Control-Allow-Origin = "https://tech-ticketing.netlify.app" }